-- AlterTable
ALTER TABLE "Event" ADD COLUMN "qrEpochAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "ClassSession" ADD COLUMN "qrEpochAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
